name: enigoma

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        working-directory: ./src
        run: go build .

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        working-directory: ./src
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        working-directory: ./src
        run: |
          go test -v ./...
