name: enigoma

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Checkout
        uses: actions/checkout@v2

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install golangci-lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
        # https://github.com/golangci/golangci-lint/issues/250
        sudo mv ./bin/golangci-lint $GOPATH/bin/
      - name: Run golangci-lint
        run: |
          golangci-lint run \
            --tests \
            --enable-all \
            --disable gochecknoglobals \
            --disable gochecknoinits

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        working-directory: ./src
        run: |
          go test -v ./...
